version: "3"
services: 
    php:
        build: .docker/php
        working_dir: /home/app
        volumes: 
            - './:/home/app/'
            - '/$USER/.composer/cache:/root/.composer/cache'
        environment: 
            - XDEBUG_SESSION=1
            - "XDEBUG_MODE=develop,debug,coverage"
            - XDEBUG_CONFIG="cli_color=1 client_host=host.docker.internal client_port=9000"